version: '3.8'

services:
  server:
    build: ./server
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build: ./client
    container_name: frontend
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    depends_on:
      - server
